### ISSUE TITLE
[iOS] .RSA.generate Not working when published on TestFlight

### ISSUE THREAD

**Issue by ZacharieAzoulai** [jerson/flutter-rsa#19]
Hi

I've been using this package for a month now and had no issue with it but yesterday when I pushed my app on Testflight, the app was working as expected,

I get this error: `'dart.core_ArgumentError_toString (kind RegularFunction)' is accessed through Dart C API without being marked as an entry point; its tree-shaken signature cannot be verified.
WARNING: See https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
`

After multiple research, I found out that it happens when calling `RSA.generate(2048);`

I was able to reproduce this error when debugging in profile mode

Do you have an idea on how to fix this ?

**Comment by jerson** [comment]
Hi @ZacharieAzoulai thanks for report the issue, im gonna try to reproduce it here in order to fix this issue

**Comment by jerson** [comment]
@ZacharieAzoulai  which version are you using ?

**Comment by ZacharieAzoulai** [comment]
I'm using the version 3.0.0

**Comment by jerson** [comment]
could you try with the previous one please https://pub.dev/packages/fast_rsa/versions/2.0.1

**Comment by jerson** [comment]
in addition to this, i tested on android release and profile mode and works for me but tomorrow i will take some time to test on ios profile and testflight

**Comment by ZacharieAzoulai** [comment]
I didn't test on android but on IOS it still doesn't work with the version 2.0.1

Thanks for your help !

**Comment by ZacharieAzoulai** [comment]
I had another error when changing to stable (I'm not sure if it's the reason) but it was also when calling `RSA.generate(2048)`

`[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'FutureOr<Uint8List>?'
#0      Binding.callAsync.<anonymous closure> (package:fast_rsa/bridge/binding.dart:49)
<asynchronous suspension>
`

Maybe it can help

**Comment by ZacharieAzoulai** [comment]
And when I display the first element of the List<dynamic> I got `Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, RSABridgeCall): symbol not found)`

**Comment by jerson** [comment]
seems like librsa_bridge.a was nor loaded properly, i tested on ios, using profile also using an adhoc release, and seems works, im using beta channel with this example project https://github.com/jerson/flutter-rsa/tree/master/example

can you share more details about for example flutter version, also if are you using bitcode, also ios target version 

about this warning:  Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'FutureOr<Uint8List>?' i can fix that

but about the main issue i still need some time to research about

**Comment by ZacharieAzoulai** [comment]
Here is my `flutter doctor -v` output:

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/zhack013/bin/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zhack013/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Zack’s iPhone (mobile) • 00008101-001D71610E51003A • ios • iOS 14.7.1

! Doctor found issues in 1 category.

My iOS target version is 9.0

**Comment by jerson** [comment]
here is my  flutter doctor -v , i havent tested before in darwin-arm im not sure if its related to this issue
```bash
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en)
    • Flutter version 2.2.3 at /Users/usuario/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/usuario/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/usuario/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/usuario/Android/Sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/usuario/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Users/usuario/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone de Stefani (mobile) • bd392d1f96cd42a46c757c355e45035718e8078b • ios            • iOS 12.5.4
    • macOS (desktop)            • macos                                    • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.

```

**Comment by ZacharieAzoulai** [comment]
So how did you make it work on your Mac ?

**Comment by jerson** [comment]
mm for me just works without any additional change in(profile, and release mode android and ios) using this example https://github.com/jerson/flutter-rsa/tree/master/example, tested using stable, and beta channels, maybe im testing in a wrong way, but for profile im using

flutter run --profile 

and for release im using xcode archive and then export using adhoc provision profile

have you tested using this example or maybe can you provide me an example project and the steps to reproduce it?

**Comment by ZacharieAzoulai** [comment]
I'll test with this example and if it works with it and not my project I'll give you an example project

**Comment by ZacharieAzoulai** [comment]
So it works with your example but not with my project, could be the fact that I'm using the flutter sdk `sdk: ">=2.7.0 <3.0.0"` ??

Does your package requires non-null safety ? or everything above 2.12 ?

**Comment by jerson** [comment]
I migrated to null-safety from 2.0.1 so you can try with an older version like 

1.3.6 or below (but since is an older version im not sure if still works)

**Comment by ZacharieAzoulai** [comment]
Hi,

I know it's been a while, I figured it out that it worked for the `RSA.generated(2048)` but now it doesn't work with `await RSA.decryptPKCS1v15`, still on version 3.0.0 and I can't test on newer version because of the path bug...

**Comment by jerson** [comment]
Hi @ZacharieAzoulai  since https://github.com/jerson/flutter-rsa/issues/22 was closed, this seems related, is this fixed for you too? or is still an issue?

**Comment by ZacharieAzoulai** [comment]
Hi @jerson, it wasn't related to it, but the only way I could fix this error was by commenting all the code and removing all my pub dependencies and uncommenting widget by widget and adding dependencies, one at a time, but I didn't found reason of this issue

I think there is like a compatibility between your packages and a mysterious one but sorry I don't know which one, the weird thing was that it wasn't causing the bug for the same method as last time...

**Comment by mohammadkarbalaee** [comment]
Guys why do you keep closing tasks that are not resolved?
It's 2025 and I am facing it.

**Comment by jerson** [comment]
I have added a branch with some changes for this issue, when you get a chance could you help me to test those please https://github.com/jerson/flutter-rsa/tree/pragma-entrypoint

**Comment by dustinkerstein** [comment]
FYI I'm seeing the same issue when using Fast RSA inside a FlutterFlow project and running a debug build locally:

`[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'RSABridgeCall': dlsym(RTLD_DEFAULT, RSABridgeCall): symbol not found`

Is there an easy way to test that branch with a package? Thanks!

**Comment by jerson** [comment]
We have just released a new version: https://pub.dev/packages/fast_rsa/versions/3.8.0, which includes two adjustments that may help with this issue:

- Added a pragma to methods used by Isolate to keep them alive in release mode.
- Introduced RSASync methods, which do not rely on Isolate and interact directly with the Bridge.

I suggest trying the new version, and if the issue persists, you can replace RSA with the new RSASync methods.

**Comment by dustinkerstein** [comment]
Hey @jerson, I just gave the new package a try and I'm running into the same issues even when trying the new RSASync methods:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'RSABridgeCall': dlsym(RTLD_DEFAULT, RSABridgeCall): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      new Binding._internal (package:fast_rsa/bridge/binding.dart)
#2      Binding._instance (package:fast_rsa/bridge/binding.dart:18:44)
#3      Binding._instance (package:fast_rsa/bridge/binding.dart)
#4      new Binding (package:fast_rsa/bridge/binding.dart:25:12)
#5      RSABridge.bindingEnabled (package:fast_rsa/fast_rsa_bridge.dart:10:38)
#6      RSABridge.bindingEnabled (package:fast_rsa/fast_rsa_bridge.dart)
#7      RSABridge.callSync (package:fast_rsa/fast_rsa_bridge.dart:21:10)
#8      RSASync.encryptPKCS1v15 (package:fast_rsa/fast_rsa_sync.dart:217:19)
#9      encryptText (package:prompts/custom_code/actions/encrypt_text.dart:22:15)
#10     _RecordButtonsWidgetState.build.<anonymous closure> (package:prompts/misc/record_buttons/record_buttons_widget.dart:396:68)
<asynchronous suspension>
#11     _RecorderState._stop (package:prompts/custom_code/widgets/recorder.dart:217:7)
<asynchronous suspension>
```

Let me know if there's something specific you'd like me to try. Thanks for your help.

**Comment by jerson** [comment]
I have been experimenting with FlutterFlow to understand what might be happening, but its free plan is limited, so I am unable to fully test this on that platform. However, here are some useful points for FlutterFlow users to consider:

- This library uses a native FFI (Foreign Function Interface) library, so it needs to be installed/copied on iOS/macOS projects by running `pod install` inside the corresponding `ios/macos` directory (standard Flutter projects handle this by default).
- For web, it is important to follow the setup guide.

> Add the following to your `pubspec.yaml`:

```yaml
assets:
  - packages/fast_rsa/web/assets/worker.js
  - packages/fast_rsa/web/assets/wasm_exec.js
  - packages/fast_rsa/web/assets/rsa.wasm
``` 

- If you have followed all these steps and still encounter the error Failed to lookup symbol, it likely means that FlutterFlow is not linking the FFI file to the project properly.
  * For iOS, the instructions to link the FFI file to the project are inside ios/fast_rsa.podspec.
  * For macOS, the instructions to link the FFI file to the project are inside macos/fast_rsa.podspec.

My suggestion is to modify these configurations, as the framework path may not be correctly set in the FlutterFlow setup.

**Comment by dustinkerstein** [comment]
FYI, I posted in the FlutterFlow GitHub repo, so we'll see if they can look into it as well. 

While this is a bit over my head, I did notice some differences between the FlutterFlow Pods-Runner.debug file and the one in the fast_rsa example iOS Xcode project. Here is the one for my FlutterFlow test project: 

```
ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES
CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = NO
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseABTesting" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseCore" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseCoreExtension" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseCoreInternal" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseFirestoreBinary" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseInstallations" "${PODS_CONFIGURATION_BUILD_DIR}/FirebasePerformance" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseRemoteConfig" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseRemoteConfigInterop" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseSessions" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseSharedSwift" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleDataTransport" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleUtilities" "${PODS_CONFIGURATION_BUILD_DIR}/PromisesObjC" "${PODS_CONFIGURATION_BUILD_DIR}/PromisesSwift" "${PODS_CONFIGURATION_BUILD_DIR}/cloud_firestore" "${PODS_CONFIGURATION_BUILD_DIR}/fast_rsa" "${PODS_CONFIGURATION_BUILD_DIR}/firebase_core" "${PODS_CONFIGURATION_BUILD_DIR}/firebase_performance" "${PODS_CONFIGURATION_BUILD_DIR}/leveldb-library" "${PODS_CONFIGURATION_BUILD_DIR}/nanopb" "${PODS_CONFIGURATION_BUILD_DIR}/path_provider_foundation" "${PODS_CONFIGURATION_BUILD_DIR}/shared_preferences_foundation" "${PODS_CONFIGURATION_BUILD_DIR}/sqflite" "${PODS_CONFIGURATION_BUILD_DIR}/url_launcher_ios" "${PODS_ROOT}/../.symlinks/plugins/fast_rsa/ios" "${PODS_ROOT}/FirebaseFirestoreAbseilBinary" "${PODS_ROOT}/FirebaseFirestoreGRPCBoringSSLBinary" "${PODS_ROOT}/FirebaseFirestoreGRPCCPPBinary" "${PODS_ROOT}/FirebaseFirestoreGRPCCoreBinary" "${PODS_ROOT}/FirebaseFirestoreInternalBinary" "${PODS_XCFRAMEWORKS_BUILD_DIR}/FirebaseFirestoreAbseilBinary" "${PODS_XCFRAMEWORKS_BUILD_DIR}/FirebaseFirestoreGRPCBoringSSLBinary" "${PODS_XCFRAMEWORKS_BUILD_DIR}/FirebaseFirestoreGRPCCPPBinary" "${PODS_XCFRAMEWORKS_BUILD_DIR}/FirebaseFirestoreGRPCCoreBinary" "${PODS_XCFRAMEWORKS_BUILD_DIR}/FirebaseFirestoreInternalBinary"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 $(inherited) PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1 PB_ENABLE_MALLOC=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseABTesting/FirebaseABTesting.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseCore/FirebaseCore.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseCoreExtension/FirebaseCoreExtension.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseCoreInternal/FirebaseCoreInternal.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseFirestoreBinary/FirebaseFirestore.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseInstallations/FirebaseInstallations.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FirebasePerformance/FirebasePerformance.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseRemoteConfig/FirebaseRemoteConfig.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseRemoteConfigInterop/FirebaseRemoteConfigInterop.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseSessions/FirebaseSessions.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseSharedSwift/FirebaseSharedSwift.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleDataTransport/GoogleDataTransport.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleUtilities/GoogleUtilities.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/PromisesObjC/FBLPromises.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/PromisesSwift/Promises.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/cloud_firestore/cloud_firestore.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/fast_rsa/fast_rsa.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/firebase_core/firebase_core.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/firebase_performance/firebase_performance.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/leveldb-library/leveldb.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/nanopb/nanopb.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/path_provider_foundation/path_provider_foundation.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/shared_preferences_foundation/shared_preferences_foundation.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/sqflite/sqflite.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/url_launcher_ios/url_launcher_ios.framework/Headers" "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Firebase" "${PODS_XCFRAMEWORKS_BUILD_DIR}/fast_rsa/Headers" $(inherited) ${PODS_ROOT}/Firebase/CoreOnly/Sources
LD_RUNPATH_SEARCH_PATHS = $(inherited) /usr/lib/swift
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_XCFRAMEWORKS_BUILD_DIR}/fast_rsa" "${TOOLCHAIN_DIR}/usr/lib/swift/${PLATFORM_NAME}" /usr/lib/swift $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)/ $(SDKROOT)/usr/lib/swift
OTHER_LDFLAGS = $(inherited) -ObjC -l"c++" -l"rsa_bridge" -l"z" -framework "CoreTelephony" -framework "FBLPromises" -framework "FirebaseABTesting" -framework "FirebaseCore" -framework "FirebaseCoreExtension" -framework "FirebaseCoreInternal" -framework "FirebaseFirestore" -framework "FirebaseFirestoreInternal" -framework "FirebaseInstallations" -framework "FirebasePerformance" -framework "FirebaseRemoteConfig" -framework "FirebaseRemoteConfigInterop" -framework "FirebaseSessions" -framework "FirebaseSharedSwift" -framework "Foundation" -framework "GoogleDataTransport" -framework "GoogleUtilities" -framework "Promises" -framework "Security" -framework "SystemConfiguration" -framework "UIKit" -framework "absl" -framework "cloud_firestore" -framework "fast_rsa" -framework "firebase_core" -framework "firebase_performance" -framework "grpc" -framework "grpcpp" -framework "leveldb" -framework "nanopb" -framework "openssl_grpc" -framework "path_provider_foundation" -framework "shared_preferences_foundation" -framework "sqflite" -framework "url_launcher_ios" -weak_framework "FirebaseFirestoreInternal"
OTHER_SWIFT_FLAGS = $(inherited) -D COCOAPODS
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
PODS_ROOT = ${SRCROOT}/Pods
PODS_XCFRAMEWORKS_BUILD_DIR = $(PODS_CONFIGURATION_BUILD_DIR)/XCFrameworkIntermediates
USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES = YES
```

And here is the fast_rsa example iOS version:

```
ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES
CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = NO
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/fast_rsa" "${PODS_CONFIGURATION_BUILD_DIR}/integration_test" "${PODS_ROOT}/../.symlinks/plugins/fast_rsa/ios"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/fast_rsa/fast_rsa.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/integration_test/integration_test.framework/Headers" "${PODS_XCFRAMEWORKS_BUILD_DIR}/fast_rsa/Headers"
LD_RUNPATH_SEARCH_PATHS = $(inherited) /usr/lib/swift '@executable_path/Frameworks' '@loader_path/Frameworks'
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_XCFRAMEWORKS_BUILD_DIR}/fast_rsa" "${TOOLCHAIN_DIR}/usr/lib/swift/${PLATFORM_NAME}" /usr/lib/swift
OTHER_LDFLAGS = $(inherited) -framework "UIKit" -framework "fast_rsa" -framework "integration_test"
OTHER_MODULE_VERIFIER_FLAGS = $(inherited) "-F${PODS_CONFIGURATION_BUILD_DIR}/Flutter" "-F${PODS_CONFIGURATION_BUILD_DIR}/fast_rsa" "-F${PODS_CONFIGURATION_BUILD_DIR}/integration_test"
OTHER_SWIFT_FLAGS = $(inherited) -D COCOAPODS
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
PODS_ROOT = ${SRCROOT}/Pods
PODS_XCFRAMEWORKS_BUILD_DIR = $(PODS_CONFIGURATION_BUILD_DIR)/XCFrameworkIntermediates
USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES = YES
```

The thing that jumped out to me was the lack of  `-ObjC -l"c++" -l"rsa_bridge" -l"z"` in the example file. Any chance that is a clue as to what's going on? Thanks!

**Comment by dustinkerstein** [comment]
And I also tried modifying the stripping settings per https://stackoverflow.com/questions/73339934/failed-to-lookup-symbol-symbol-not-found-when-running-flutter-plugin-with-nat but it results in the same error.

**Comment by dustinkerstein** [comment]
@jerson, let me know if you'd be up for me paying for a month of FlutterFlow so you can test locally. I'd be happy to do that. Thanks!

**Comment by jerson** [comment]
Hi @dustinkerstein it seems they provide a trial, going to take a look again in a few days to understand what's different with them

**Comment by jerson** [comment]
a fix was released in https://pub.dev/packages/fast_rsa/versions/3.8.2 please take a look and let me know if works for you, I already tested in FlutterFlow and seems working fine

**Comment by dustinkerstein** [comment]
Just gave 3.8.2 version a quick test and it looks like it somehow causes an issue with other packages (ie. Firestore). See the attached [Debug.log](https://github.com/user-attachments/files/19797200/Debug.log) - When I downgrade to 3.8.1 everything goes back to how it was. Would you be able to try enabling Firestore within FlutterFlow to see if you can replicate those build symbol errors? Thanks again for looking into this.

**Comment by dustinkerstein** [comment]
Removing -Objc from Other Linker Flags in Build Settings appears to fix this issue (found via https://github.com/firebase/flutterfire/issues/10709#issuecomment-1652419747) and gets fast_rsa running on iOS for me within FlutterFlow. But I'm not entirely sure if that's safe to do (and requires a manual hack). Is that flag being added via fast_rsa or from FlutterFlow/Firestore?

**Comment by jerson** [comment]
I’m able to reproduce this issue. I tried several combinations to fix it, but without success. It’s odd because we don’t reference Objective-C anywhere, so this might be something the Firestore library needs to address on their end. I’ll refactor the XCFramework build process to avoid using force-loads, but that likely won’t resolve the issue either

**Comment by dustinkerstein** [comment]
Interesting. Let me know how it goes and if there's anything I can help test. Thanks for looking into this.

**Comment by jerson** [comment]
Hi @dustinkerstein a new version was released: https://pub.dev/packages/fast_rsa/versions/3.8.3 could you take a look please and let me know if works for you?

**Comment by dustinkerstein** [comment]
@jerson Nice! This is looking perfect. No conflicts with Firebase and no workarounds necessary. Thanks so much!

**Comment by mo-karbalaee** [comment]
I am struggling with the same issue on version: 3.8.5.

I changed my method and migrated to the other packages. Solved my issue. 
Tschüss

**Comment by sylduc** [comment]
> Just gave 3.8.2 version a quick test and it looks like it somehow causes an issue with other packages (ie. Firestore). See the attached [Debug.log](https://github.com/user-attachments/files/19797200/Debug.log) - When I downgrade to 3.8.1 everything goes back to how it was. Would you be able to try enabling Firestore within FlutterFlow to see if you can replicate those build symbol errors? Thanks again for looking into this.

It's working whatever the version in dev mode

BUT... On the 3.8.1 - tests from TestFlight are working
WHERE in the above versions (I currently tried with the 3.8.6) it's NOT WORKING from TestFlight
