### ISSUE TITLE
Failed to load dynamic library 'librsa_bridge.dylib'

### ISSUE THREAD

**Issue by enricocaliolo** [jerson/flutter-rsa#46]
I am trying to test some functions using Mockito, but when I try to call it, it throws an error. It works fine in the application itself, but in the tests don't.

This is the test:
```
test('Public and private key should not be null when generated', () async {
      final MockRSAKeysProvider rsaKeys = MockRSAKeysProvider();

      when(rsaKeys.generate(any)).thenAnswer((value) async {
        KeyPair keyPair = await RSA.generate(2048);
        rsaKeys.setKeyPair = keyPair;
      });

      await rsaKeys.generate('2048');

      verify(rsaKeys.notifyListeners()).called(1);
      expect(rsaKeys.keyPair?.privateKey, isNotNull);
      expect(rsaKeys.keyPair?.publicKey, isNotNull);
    });
```

This is the code I am testing:

```
class RSAKeysProvider with ChangeNotifier {
 KeyPair? _keyPair;

  KeyPair? get keyPair => _keyPair;
  set setKeyPair(KeyPair keyPair) => _keyPair = keyPair;

Future<void> generate(String bits) async {
    var keyPair = await RSA.generate(int.parse(bits));
    _keyPair = keyPair;
    notifyListeners();
  }
}
```

And this is the error I am getting:

```
Error Invalid argument(s): Failed to load dynamic library 'librsa_bridge.dylib': dlopen(librsa_bridge.dylib, 0x0001): tried: 'librsa_bridge.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibrsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/./librsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/../../../librsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/Frameworks/librsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/./librsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/../../../librsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/Frameworks/librsa_bridge.dylib' (no such file), '/usr/lib/librsa_bridge.dylib' (no such file, not in dyld cache), 'librsa_bridge.dylib' (no such file), '/usr/lib/librsa_bridge.dylib' (no such file, not in dyld cache)
Stack trace #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      Binding.openLib (package:fast_rsa/bridge/binding.dart:117:33)
#3      new Binding._internal (package:fast_rsa/bridge/binding.dart:26:16)
#4      Binding._singleton (package:fast_rsa/bridge/binding.dart:17:45)
#5      Binding._singleton (package:fast_rsa/bridge/binding.dart)
#6      new Binding (package:fast_rsa/bridge/binding.dart:22:12)
#7      RSA.bindingEnabled (package:fast_rsa/fast_rsa.dart:40:32)
#8      RSA.bindingEnabled (package:fast_rsa/fast_rsa.dart)
#9      RSA._call (package:fast_rsa/fast_rsa.dart:43:9)
#10     RSA._keyPairResponse (package:fast_rsa/fast_rsa.dart:79:22)
#11     RSA.generate (package:fast_rsa/fast_rsa.dart:437:18)
#12     main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/enrico/Developer/flutter/labsec-desafio/test/rsa_keys.test.dart:33:39)
#13     Mock.noSuchMethod (package:mockito/src/mock.dart:185:45)
#14     MockRSAKeysProvider.generate (file:///Users/enrico/Developer/flutter/labsec-desafio/test/rsa_keys.test.mocks.dart:75:53)
#15     main.<anonymous closure>.<anonymous closure> (file:///Users/enrico/Developer/flutter/labsec-desafio/test/rsa_keys.test.dart:37:23)
#16     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
<asynchronous suspension>
#17     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
```

Running with Flutter 3.7.3, fast_rsa 3.5.3, mockito 5.3.2, test 1.22.0

**Comment by jerson** [comment]
Hi, currently it can't be executed in unit tests, we are currently working to support this

**Comment by enricocaliolo** [comment]
oh, thanks for the fast response! Good to know, will be waiting for upcoming releases then.

**Comment by jerson** [comment]
Hi @enricocaliolo I'm adding a new PR to fix this, just in case you want to take a look

**Comment by jerson** [comment]
New version released https://pub.dev/packages/fast_rsa/versions/3.5.5 please try with this one, feel free to reopen the issue if its needed

**Comment by enricocaliolo** [comment]
HI, now I'm getting a different error, with the same code. Could it be related to the fact that I'm using a Macbook.

```
Invalid argument(s): Failed to load dynamic library 'build/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib': dlopen(build/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib, 0x0001): tried: 'build/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSbuild/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/./build/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/../../../build/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/Frameworks/build/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/./build/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/../../../build/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib' (no such file), '/opt/homebrew/Caskroom/flutter/3.7.3/flutter/bin/cache/artifacts/engine/darwin-x64/Frameworks/build/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib' (no such file), '/usr/lib/build/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib' (no such file, not in dyld cache), 'build/macos/Build/Products/Debug/fast_rsa/fast_rsa.framework/Resources/librsa_bridge.dylib' (no such file)
  dart:ffi                                                       new DynamicLibrary.open
  package:fast_rsa/bridge/binding.dart 120:35                    Binding.openLib
  package:fast_rsa/bridge/binding.dart 26:16                     new Binding._internal
  package:fast_rsa/bridge/binding.dart 17:45                     Binding._singleton
  package:fast_rsa/bridge/binding.dart                           Binding._singleton
  package:fast_rsa/bridge/binding.dart 22:12                     new Binding
  package:fast_rsa/fast_rsa.dart 39:32                           RSA.bindingEnabled
  package:fast_rsa/fast_rsa.dart                                 RSA.bindingEnabled
  package:fast_rsa/fast_rsa.dart 42:9                            RSA._call
  package:fast_rsa/fast_rsa.dart 78:22                           RSA._keyPairResponse
  package:fast_rsa/fast_rsa.dart 436:18                          RSA.generate
  package:labsec_desafio_principal/providers/rsa_key.dart 20:33  RSAKeysProvider.generate
  test/rsa_keys.test.dart 25:21                                  main.<fn>.<fn>
```

**Comment by jerson** [comment]
HI @enricocaliolo cloud you try run the project in macos first, that's a required step in order to have that file there

`flutter run -d macos`

**Comment by enricocaliolo** [comment]
oh, now it worked. Thanks for your hard work!

**Comment by ShikiFuujin** [comment]
good day, im trying to do an unit test where a use 'encryptOAEP', im getting the same error ... the problem is that is a plugin project , not an app project and therefore there is not a lib/main.dart file , the 'flutter run -d macos' is not working for me

` static Future<String> encryptText(
    String text,
    String publicTextKey,
  ) async {
    return await fastRsa.RSA.encryptOAEP(
      text,
      '',
      fastRsa.Hash.SHA256,
      publicTextKey,
    );
  }`

**Comment by guenesyurdakul** [comment]
> HI [@enricocaliolo](https://github.com/enricocaliolo) cloud you try run the project in macos first, that's a required step in order to have that file there
> 
> `flutter run -d macos`

I am using your library in a flutter project that supports only ios and android. So to be able to add tests, will i need to add macOs support? 
This doesn't seem like a good approach. is it planned to make testing not macOs dependant?
