### ISSUE TITLE
RSA.generate in Browser:  Refused to execute script... MIME type ('text/html') is not executable

### ISSUE THREAD

**Issue by xErik** [jerson/flutter-rsa#68]
Thank your for the library!

Is it supposed to work in a web environment?

Running this code in the latest Chrome results in the error below. 

Debug mode.

```dart
await fast.RSA.generate(2048);
```

```
Refused to execute script from 'http://localhost:63079/assets/packages/fast_rsa/web/assets/worker.js' 
because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

Deployed to a server this error occurs:

```
main.dart.js:5146 Uncaught MissingPluginException(No implementation found for method generate on channel fast_rsa)
    at Object.c (https://XXXXXXXXXX/main.dart.js:5146:19)
    at https://XXXXXXXXXX/main.dart.js:89698:15
    at aWO.a (https://XXXXXXXXXX/main.dart.js:6521:63)
    at aWO.$2 (https://XXXXXXXXXX/main.dart.js:50328:14)
    at aVt.$1 (https://XXXXXXXXXX/main.dart.js:50322:21)
    at aSg.aKJ (https://XXXXXXXXXX/main.dart.js:51171:34)
    at aSg.B8 (https://XXXXXXXXXX/main.dart.js:51174:13)
    at aOx.$0 (https://XXXXXXXXXX/main.dart.js:50750:11)
    at Object.Ca (https://XXXXXXXXXX/main.dart.js:6653:40)
    at ax.tA (https://XXXXXXXXXX/main.dart.js:50685:3)
```

**Comment by jerson** [comment]
Hi @xErik have you read the instructions for web? You also need to make sure you web server is using the right content type for wasm files
